### PR TITLE
move exports default to the end

### PR DESCRIPTION
**Pull request by nam-truong-le**
This is an error I got in nextjs:

```
Module not found: Default condition should be last one
```

### CODE REVIEW

**Comment by nam-truong-le** [comment]
@viclafouch Can you have a look? Thank you.

**Comment by nam-truong-le** [comment]
@viclafouch Thank you very much. When are you going to create a new release?

**Comment by viclafouch** [comment]
asap :)

**Comment by viclafouch** [comment]
Released :)

**Pull request merged**
